name: Build and Deploy RankMonkey.Server

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'RankMonkey.Server/RankMonkey.Server.csproj'
  PUBLISH_PATH: '${{ github.workspace }}/publish'
  DEPLOY_PATH: '/apps/rankmonkey/server/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_PATH }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{ env.PUBLISH_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app
        path: ${{ env.PUBLISH_PATH }}

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_DEPLOY_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
        name: id_ed25519
        config: |
          Host ${{ secrets.SERVER_HOST }}
            HostName ${{ secrets.SERVER_HOST }}
            User ${{ secrets.SERVER_USER }}
            Port 22222
            IdentityFile ~/.ssh/id_ed25519

    - name: Debug SSH
      run: |
        echo "SSH key file permissions:"
        ls -l ~/.ssh
        echo "SSH config:"
        cat ~/.ssh/config
        echo "Known hosts:"
        cat ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -v ${{ secrets.SERVER_HOST }} "echo 'SSH connection successful'"

    - name: Deploy to VPS
      run: |
        scp -v -P 22222 -r ${{ env.PUBLISH_PATH }}/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ env.DEPLOY_PATH }}
        ssh -t -p 22222 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo -n systemctl restart rankmonkey.service || echo 'Failed to restart service'"